In [1]:
import pandas as pd
import plotly.graph_objects as go
import nfl_data_py as nfl

In [ ]:
## get the total for the season for each player

year_list = [2024]
df = nfl.import_seasonal_data(year_list)
id_df = nfl.import_ids()
id_df = id_df[['gsis_id','name']]
df = pd.merge(df,  
                    id_df,  
                    left_on = 'player_id',
                    right_on = 'gsis_id',
                    how ='left')
df

,player_id,season,season_type,completions,attempts,passing_yards,passing_tds,interceptions,sacks,sack_yards,...,ry_sh,rtd_sh,rfd_sh,rtdfd_sh,dom,w8dom,yptmpa,ppr_sh,gsis_id,name
0,00-0023459,2024,REG,368,584,3897.0,28,11.0,40.0,302.0,...,0.000000,0.00,0.000000,0.000000,0.000000,0.000000,0.000000,0.177032,00-0023459,Aaron Rodgers
1,00-0024243,2024,REG,0,0,0.0,0,0.0,0.0,0.0,...,0.008850,0.00,0.071429,0.055556,0.004425,0.007080,0.068966,0.010541,00-0024243,Marcedes Lewis
2,00-0026158,2024,REG,162,248,1761.0,12,7.0,18.0,123.0,...,0.000000,0.00,0.000000,0.000000,0.000000,0.000000,0.000000,0.156155,00-0026158,Joe Flacco
3,00-0026300,2024,REG,2,3,17.0,0,0.0,1.0,5.0,...,0.000000,0.00,0.000000,0.000000,0.000000,0.000000,0.000000,0.001842,00-0026300,Josh Johnson
4,00-0026498,2024,REG,340,517,3762.0,20,8.0,28.0,213.0,...,0.000000,0.00,0.000000,0.000000,0.000000,0.000000,0.000000,0.164457,00-0026498,Matthew Stafford
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
602,00-0039917,2024,REG,61,105,775.0,3,3.0,4.0,14.0,...,0.000000,0.00,0.000000,0.000000,0.000000,0.000000,0.000000,0.107378,00-0039917,Michael Penix Jr.
603,00-0039918,2024,REG,351,562,3541.0,20,6.0,68.0,466.0,...,0.000000,0.00,0.000000,0.000000,0.000000,0.000000,0.000000,0.196150,00-0039918,Caleb Williams
604,00-0039919,2024,REG,0,0,0.0,0,0.0,0.0,0.0,...,0.206644,0.15,0.215116,0.208333,0.178322,0.195315,1.296820,0.111661,00-0039919,Rome Odunze
605,00-0039920,2024,REG,0,0,0.0,0,0.0,0.0,0.0,...,0.017641,0.00,0.020408,0.017241,0.008820,0.014112,0.096970,0.018849,00-0039920,Malachi Corley
606,00-0039921,2024,REG,0,0,0.0,0,0.0,0.0,0.0,...,0.021423,0.00,0.023077,0.020979,0.010712,0.017139,0.158602,0.047205,00-0039921,Trey Benson

In [ ]:
## get the weekly data for each player
df = nfl.import_weekly_data([2024])
df

Downcasting floats.

,player_id,player_name,player_display_name,position,position_group,headshot_url,recent_team,season,week,season_type,...,receiving_first_downs,receiving_epa,receiving_2pt_conversions,racr,target_share,air_yards_share,wopr,special_teams_tds,fantasy_points,fantasy_points_ppr
0,00-0023459,A.Rodgers,Aaron Rodgers,QB,QB,https://static.www.nfl.com/image/upload/f_auto...,NYJ,2024,1,REG,...,0.0,NaN,0,NaN,NaN,NaN,NaN,0.0,8.580000,8.580000
1,00-0023459,A.Rodgers,Aaron Rodgers,QB,QB,https://static.www.nfl.com/image/upload/f_auto...,NYJ,2024,2,REG,...,0.0,NaN,0,NaN,NaN,NaN,NaN,0.0,15.140000,15.140000
2,00-0023459,A.Rodgers,Aaron Rodgers,QB,QB,https://static.www.nfl.com/image/upload/f_auto...,NYJ,2024,3,REG,...,0.0,NaN,0,NaN,NaN,NaN,NaN,0.0,21.040001,21.040001
3,00-0023459,A.Rodgers,Aaron Rodgers,QB,QB,https://static.www.nfl.com/image/upload/f_auto...,NYJ,2024,4,REG,...,0.0,NaN,0,NaN,NaN,NaN,NaN,0.0,11.600000,11.600000
4,00-0023459,A.Rodgers,Aaron Rodgers,QB,QB,https://static.www.nfl.com/image/upload/f_auto...,NYJ,2024,5,REG,...,0.0,NaN,0,NaN,NaN,NaN,NaN,0.0,11.760000,11.760000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5592,00-0039921,T.Benson,Trey Benson,RB,RB,https://static.www.nfl.com/image/upload/f_auto...,ARI,2024,10,REG,...,2.0,1.987017,0,-3.125,0.083333,-0.072072,0.074550,0.0,8.700000,10.700000
5593,00-0039921,T.Benson,Trey Benson,RB,RB,https://static.www.nfl.com/image/upload/f_auto...,ARI,2024,12,REG,...,0.0,NaN,0,NaN,NaN,NaN,NaN,0.0,1.800000,1.800000
5594,00-0039921,T.Benson,Trey Benson,RB,RB,https://static.www.nfl.com/image/upload/f_auto...,ARI,2024,13,REG,...,0.0,NaN,0,NaN,NaN,NaN,NaN,0.0,2.000000,2.000000
5595,00-0039921,T.Benson,Trey Benson,RB,RB,https://static.www.nfl.com/image/upload/f_auto...,ARI,2024,14,REG,...,0.0,-0.144496,0,-0.800,0.026316,-0.031847,0.017181,0.0,1.900000,2.900000
5596,00-0039921,T.Benson,Trey Benson,RB,RB,https://static.www.nfl.com/image/upload/f_auto...,ARI,2024,15,REG,...,0.0,NaN,0,NaN,NaN,NaN,NaN,0.0,2.200000,2.200000

In [19]:
df = nfl.import_ngs_data('passing', [2024])

df

,season,season_type,week,player_display_name,player_position,team_abbr,avg_time_to_throw,avg_completed_air_yards,avg_intended_air_yards,avg_air_yards_differential,...,completion_percentage,expected_completion_percentage,completion_percentage_above_expectation,avg_air_distance,max_air_distance,player_gsis_id,player_first_name,player_last_name,player_jersey_number,player_short_name
4714,2024,REG,0,Jalen Hurts,QB,PHI,3.131300,6.202016,7.991677,-1.789661,...,68.698061,62.088260,6.609801,21.781763,59.287984,00-0036389,Jalen,Hurts,1,J.Hurts
4715,2024,REG,0,Sam Darnold,QB,MIN,3.083395,6.935817,8.884583,-1.948765,...,66.238532,63.015796,3.222736,22.138207,55.646285,00-0034869,Sam,Darnold,14,S.Darnold
4716,2024,REG,0,Deshaun Watson,QB,CLE,2.938977,3.853504,7.149143,-3.295639,...,63.425926,65.573537,-2.147611,19.757465,58.675437,00-0033537,Derrick,Watson,4,D.Watson
4717,2024,REG,0,Kirk Cousins,QB,ATL,2.708490,5.832706,7.801693,-1.968987,...,66.887417,64.553796,2.333621,21.189211,54.513717,00-0029604,Kirk,Cousins,18,K.Cousins
4718,2024,REG,0,Aidan O'Connell,QB,LV,2.915640,5.638636,7.744655,-2.106019,...,63.374486,61.930484,1.444002,21.214375,52.572868,00-0038579,Aidan,O'Connell,12,A.O'Connell
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5323,2024,POST,21,Patrick Mahomes,QB,KC,2.594154,5.234444,6.793200,-1.558756,...,69.230769,70.506506,-1.275737,19.948697,42.749331,00-0033873,Patrick,Mahomes,15,P.Mahomes
5324,2024,POST,21,Jayden Daniels,QB,WAS,2.709000,4.764138,7.153043,-2.388906,...,60.416667,68.881243,-8.464577,21.308467,44.512399,00-0039910,Jayden,Daniels,5,J.Daniels
5325,2024,POST,21,Josh Allen,QB,BUF,2.918647,4.970000,7.555806,-2.585806,...,64.705882,65.173744,-0.467862,20.560432,44.509533,00-0034857,Joshua,Allen,17,J.Allen
5326,2024,POST,23,Patrick Mahomes,QB,KC,3.067875,8.114286,7.977813,0.136473,...,65.625000,70.818832,-5.193832,20.038168,64.377967,00-0033873,Patrick,Mahomes,15,P.Mahomes
5327,2024,POST,23,Jalen Hurts,QB,PHI,3.369182,7.905294,8.321818,-0.416524,...,77.272727,64.632090,12.640637,24.318530,54.877582,00-0036389,Jalen,Hurts,1,J.Hurts

In [22]:
df = nfl.import_ftn_data([2024])
# print( df.columns )
df

Downcasting floats.

,ftn_game_id,nflverse_game_id,season,week,ftn_play_id,nflverse_play_id,starting_hash,qb_location,n_offense_backfield,n_defense_box,...,read_thrown,is_catchable_ball,is_contested_ball,is_created_reception,is_drop,is_qb_sneak,n_blitzers,n_pass_rushers,is_qb_fault_sack,date_pulled
0,6449,2024_01_BAL_KC,2024,1,1057995,43,0,0,0,0,...,0,False,False,False,False,False,0,0,False,2024-11-07 12:32:20.655396
1,6449,2024_01_BAL_KC,2024,1,1057996,60,L,S,1,7,...,0,False,False,False,False,False,0,0,False,2024-11-07 12:32:20.655396
2,6449,2024_01_BAL_KC,2024,1,1057997,82,L,S,0,6,...,1,True,False,False,False,False,0,4,False,2024-11-07 12:32:20.655396
3,6449,2024_01_BAL_KC,2024,1,1057998,118,L,S,1,6,...,CHK,True,False,False,False,False,0,4,False,2024-11-07 12:32:20.655396
4,6449,2024_01_BAL_KC,2024,1,1057999,148,R,S,1,6,...,CHK,True,False,False,False,False,1,5,False,2024-11-07 12:32:20.655396
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
48026,6733,2024_22_KC_PHI,2024,22,1106021,4145,L,S,0,5,...,1,True,True,False,False,False,0,4,False,2025-02-14 18:20:46.105438
48027,6733,2024_22_KC_PHI,2024,22,1106022,4158,0,0,0,0,...,0,False,False,False,False,False,0,0,False,2025-02-14 18:20:46.105438
48028,6733,2024_22_KC_PHI,2024,22,1106023,4181,0,0,0,0,...,0,False,False,False,False,False,0,0,False,2025-02-14 18:20:46.105438
48029,6733,2024_22_KC_PHI,2024,22,1106024,4203,0,0,0,0,...,0,False,False,False,False,False,0,0,False,2025-02-14 18:20:46.105438
48030,6733,2024_22_KC_PHI,2024,22,1106025,4225,0,0,0,0,...,0,False,False,False,False,False,0,0,False,2025-02-14 18:20:46.105438

In [23]:
nfl.see_pbp_cols()

Index(['play_id', 'game_id', 'old_game_id', 'home_team', 'away_team',
       'season_type', 'week', 'posteam', 'posteam_type', 'defteam',
       ...
       'out_of_bounds', 'home_opening_kickoff', 'qb_epa', 'xyac_epa',
       'xyac_mean_yardage', 'xyac_median_yardage', 'xyac_success', 'xyac_fd',
       'xpass', 'pass_oe'],
      dtype='object', length=372)